import { defineConfig } from 'oxlint'

export default defineConfig({
	ignorePatterns: [
		'.agent/**',
		'.agents/**',
		'.claude/**',
		'.codex/**',
		'.continue/**',
		'.cursor/**',
		'.gemini/**',
		'.humanlayer/**',
		'.opencode/**',
		'.pi/**',
		'.roo/**',
		'.windsurf/**',
		'tools/oxlint/anti-slop/**',
		'tools/oxlint/automation/**',
		'tools/diff-check/**',
		'tools/typed/**',
	],
	jsPlugins: [
		{
			name: 'anti-slop',
			specifier: './tools/oxlint/anti-slop/index.ts',
		},
		{
			name: 'automation',
			specifier: './tools/oxlint/automation/index.ts',
		},
		'eslint-plugin-better-tailwindcss',
	],
	categories: {
		correctness: 'error',
		suspicious: 'warn',
	},
	settings: {
		'better-tailwindcss': {
			entryPoint: './tools/oxlint/tailwind/policy.css',
		},
	},
	rules: {
		'anti-slop/no-chained-type-assertions': 'error',
		'anti-slop/no-conditional-empty-array-spread': 'error',
		'anti-slop/no-conditional-empty-object-spread': 'error',
		'anti-slop/no-known-value-widening': 'error',
		'anti-slop/no-module-mocking': 'error',
		'anti-slop/no-object-parameters': 'error',
		'anti-slop/no-reflect-apply': 'error',
		'anti-slop/no-reflect-get': 'error',
		'anti-slop/no-runtime-typeof': 'error',
		'anti-slop/no-shape-in-symbol-names': 'error',
		'anti-slop/no-unknown-parameters': 'error',
		'anti-slop/no-unknown-returns': 'error',
		'anti-slop/no-unknown-type-aliases': 'error',
		'anti-slop/no-unsafe-dictionary-type': 'error',
		'anti-slop/no-widen-then-assert': 'error',
		'anti-slop/require-safety-comment-for-type-assertion': 'error',
		'automation/prefer-tagged-error-handling': 'error',
		'better-tailwindcss/no-concatenated-classes': 'error',
		'better-tailwindcss/no-conflicting-classes': 'error',
		'better-tailwindcss/no-deprecated-classes': 'error',
		'better-tailwindcss/no-duplicate-classes': 'error',
		'better-tailwindcss/no-restricted-classes': ['error', { restrict: ['\\[[^\\]]+\\]'] }],
		'better-tailwindcss/no-unknown-classes': 'error',
		'no-console': 'error',
		'no-empty': 'error',
		'no-empty-function': 'warn',
		'no-eq-null': 'error',
		'no-unused-vars': 'warn',
		'unicorn/filename-case': 'error',
		'require-yield': 'off',
		'no-shadow': 'off',
		'no-img-element': 'off',
		'react-in-jsx-scope': 'off',
		'exhaustive-deps': 'off',
	},
})
