import { recommended } from '@effect/tsgo/oxlint-presets'
import { defineConfig } from 'vite-plus'

export default defineConfig({
	envDir: false,
	staged: {
		'*': 'vp check --fix',
	},
	test: {
		include: ['packages/*/test/**/*.test.ts', 'examples/*/test/**/*.test.ts'],
		exclude: [
			'**/node_modules/**',
			'**/dist/**',
			'**/test-backends/**',
			'**/*.postgres.test.ts',
			'**/*.redis.test.ts',
			'tools/oxlint/anti-slop/**',
		],
		passWithNoTests: true,
		silent: 'passed-only',
	},
	lint: {
		extends: [recommended],
		plugins: ['typescript', 'oxc', 'vitest', 'effecttsgo'],
		options: {
			typeAware: true,
			typeCheck: true,
		},
		jsPlugins: [
			{ name: 'import-extensions', specifier: './tools/oxlint/import-extensions.mjs' },
			{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' },
			{ name: 'anti-slop', specifier: './tools/oxlint/dist/index.js' },
			{
				name: 'anti-slop-effect',
				specifier: './tools/oxlint/dist/effect/index.js',
			},
		],
		ignorePatterns: [
			'**/node_modules/**',
			'**/dist/**',
			'**/.alchemy/**',
			'.agent/**',
			'.agents/**',
			'.claude/**',
			'.codex/**',
			'.continue/**',
			'.cursor/**',
			'.gemini/**',
			'.humanlayer/**',
			'.opencode/**',
			'.pi/**',
			'.roo/**',
			'.windsurf/**',
			'tools/oxlint/anti-slop/**',
		],
		rules: {
			'import-extensions/no-relative-source-extensions': 'error',
			'vite-plus/prefer-vite-plus-imports': 'error',
			'anti-slop/no-chained-type-assertions': 'error',
			'anti-slop/no-comments': 'error',
			'anti-slop/no-conditional-empty-object-spread': 'error',
			'anti-slop/no-known-value-widening': 'error',
			'anti-slop/no-module-mocking': 'error',
			'anti-slop/no-object-parameters': 'error',
			'anti-slop/no-reflect-apply': 'error',
			'anti-slop/no-reflect-get': 'error',
			'anti-slop/no-runtime-typeof': 'error',
			'anti-slop/no-shape-in-symbol-names': 'error',
			'anti-slop/no-unknown-parameters': 'error',
			'anti-slop/no-unknown-returns': 'error',
			'anti-slop/no-unknown-type-aliases': 'error',
			'anti-slop/no-unsafe-dictionary-type': 'error',
			'anti-slop/no-widen-then-assert': 'error',
			'anti-slop/require-safety-comment-for-type-assertion': 'error',
			'anti-slop-effect/no-manual-effect-error-tag': 'error',
			'anti-slop-effect/no-manual-tag-comparison': 'error',
			'anti-slop-effect/no-manual-tagged-construction': 'error',
			'anti-slop-effect/prefer-effect-match': 'error',
			complexity: ['error', { max: 20 }],
		},
		overrides: [
			{
				files: ['**/test/**', '**/test-backends/**', '**/*.test.ts'],
				rules: {
					'anti-slop-effect/no-manual-tagged-construction': 'off',
				},
			},
		],
	},
	fmt: {
		printWidth: 120,
		tabWidth: 4,
		useTabs: true,
		singleQuote: true,
		semi: false,
		sortImports: true,
		ignorePatterns: [
			'**/node_modules/**',
			'**/dist/**',
			'.agents/**',
			'.claude/**',
			'.humanlayer/**',
			'tools/oxlint/anti-slop/**',
		],
	},
	run: {
		cache: true,
	},
})
