import { recommended } from '@effect/tsgo/oxlint-presets'
import { defineConfig } from 'vite-plus'

export default defineConfig({
	envDir: false,
	staged: {
		'*': 'vp check --fix',
	},
	test: {
		include: ['packages/*/test/**/*.test.ts', 'examples/*/test/**/*.test.ts'],
		exclude: [
			'**/node_modules/**',
			'**/dist/**',
			'**/test-backends/**',
			'**/*.postgres.test.ts',
			'**/*.redis.test.ts',
			'tools/oxlint/anti-slop/**',
		],
		passWithNoTests: true,
		silent: 'passed-only',
	},
	lint: {
		extends: [recommended],
		plugins: ['typescript', 'oxc', 'vitest', 'effecttsgo'],
		options: {
			typeAware: true,
			typeCheck: true,

		},
		jsPlugins: [
			{ name: 'import-extensions', specifier: './tools/oxlint/import-extensions.mjs' },
			{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' },
			{ name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' },
			{ name: 'automation', specifier: './tools/oxlint/automation/index.ts' },
			'eslint-plugin-better-tailwindcss',
			{
				name: 'anti-slop-effect',
				specifier: './tools/oxlint/anti-slop/effect/index.ts',
			},
		],
		ignorePatterns: [
			'**/node_modules/**',
			'**/dist/**',
			'**/.alchemy/**',
			'.agent/**',
			'.agents/**',
			'.claude/**',
			'.codex/**',
			'.continue/**',
			'.cursor/**',
			'.gemini/**',
			'.humanlayer/**',
			'.opencode/**',
			'.pi/**',
			'.roo/**',
			'.windsurf/**',
			'tools/oxlint/anti-slop/**',
			'tools/oxlint/automation/**',
			'tools/diff-check/**',
			'tools/typed/**',
			'scripts/**',
		],
		categories: {
			correctness: 'error',
			suspicious: 'warn',
		},
		settings: {
			'better-tailwindcss': {
				entryPoint: './tools/oxlint/tailwind/policy.css',
			},
		},
		rules: {
			'import-extensions/no-relative-source-extensions': 'error',
			'vite-plus/prefer-vite-plus-imports': 'error',
			'anti-slop/no-chained-type-assertions': 'error',
			'anti-slop/no-comments': 'error',
			'anti-slop/no-conditional-empty-array-spread': 'error',
			'anti-slop/no-conditional-empty-object-spread': 'error',
			'anti-slop/no-known-value-widening': 'error',
			'anti-slop/no-module-mocking': 'error',
			'anti-slop/no-object-parameters': 'error',
			'anti-slop/no-reflect-apply': 'error',
			'anti-slop/no-reflect-get': 'error',
			'anti-slop/no-runtime-typeof': 'error',
			'anti-slop/no-shape-in-symbol-names': 'error',
			'anti-slop/no-unknown-parameters': 'error',
			'anti-slop/no-unknown-returns': 'error',
			'anti-slop/no-unknown-type-aliases': 'error',
			'anti-slop/no-unsafe-dictionary-type': 'error',
			'anti-slop/no-widen-then-assert': 'error',
			'anti-slop/require-safety-comment-for-type-assertion': 'error',
			'anti-slop-effect/no-manual-effect-error-tag': 'error',
			'anti-slop-effect/no-manual-tag-comparison': 'error',
			'anti-slop-effect/no-manual-tagged-construction': 'error',
			'anti-slop-effect/no-manual-tagged-type': 'error',
			'anti-slop-effect/prefer-effect-match': 'error',
			'automation/no-ambient-nondeterminism': 'error',
			'automation/no-api-backend-imports': 'error',
			'automation/no-api-repository-imports': 'error',
			'automation/no-banned-type-assertions': 'error',
			'automation/no-cascading-layer-provide': 'off',
			'automation/no-comments': 'off',
			'automation/no-css-modules': 'error',
			'automation/no-direct-browser-storage': 'error',
			'automation/no-direct-fetch': 'error',
			'automation/no-direct-xstate-create-machine': 'error',
			'automation/no-direct-xstate-use-selector': 'error',
			'automation/no-disable-validation': 'error',
			'automation/no-effect-asvoid': 'off',
			'automation/no-fixed-height-on-content': 'error',
			'automation/no-global-json': 'off',
			'automation/no-in-operator': 'error',
			'automation/no-jsx-style': 'error',
			'automation/no-multiple-function-params': 'off',
			'automation/no-multiple-xstate-hooks': 'error',
			'automation/no-nested-effect-array-methods': 'error',
			'automation/no-nested-layer-provide': 'error',
			'automation/no-non-route-layout-files': 'error',
			'automation/no-optional-function-parameters': 'off',
			'automation/no-react-component-inner-functions': 'error',
			'automation/no-react-non-component-function-exports': 'error',
			'automation/no-react-state-hooks': 'error',
			'automation/no-reexport-only-modules': 'off',
			'automation/no-service-option': 'error',
			'automation/no-shadowed-standard-array-static': 'error',
			'automation/no-silent-error-swallow': 'error',
			'automation/no-single-use-private-functions': 'off',
			'automation/no-single-use-xstate-actions': 'error',
			'automation/no-single-use-xstate-guards': 'error',
			'automation/no-sql-type-parameter': 'error',
			'automation/no-static-effect-service-forwarders': 'error',
			'automation/no-switch': 'error',
			'automation/no-try-catch': 'error',
			'automation/no-type-assertion': 'error',
			'automation/no-typeof-object': 'error',
			'automation/pipe-max-arguments': 'error',
			'automation/prefer-effect-match': 'error',
			'automation/prefer-option-from-nullable': 'error',
			'automation/prefer-tagged-error-handling': 'error',
			'automation/private-function-prefix': 'off',
			'automation/require-approved-ui-primitives': 'error',
			'automation/require-cn-for-classname-composition': 'error',
			'automation/require-context-service-in-services': 'error',
			'automation/require-default-component-export': 'error',
			'automation/require-tsx-in-ui-folders': 'error',
			'automation/require-xstate-event-satisfies': 'error',
			'better-tailwindcss/no-concatenated-classes': 'error',
			'better-tailwindcss/no-conflicting-classes': 'error',
			'better-tailwindcss/no-deprecated-classes': 'error',
			'better-tailwindcss/no-duplicate-classes': 'error',
			'better-tailwindcss/no-restricted-classes': ['error', { restrict: ['\\[[^\\]]+\\]'] }],
			'better-tailwindcss/no-unknown-classes': 'error',
			complexity: ['error', { max: 20 }],
			'no-console': 'error',
			'no-empty': 'error',
			'no-empty-function': 'warn',
			'no-eq-null': 'error',
			'no-unused-vars': 'warn',
			'unicorn/filename-case': 'error',
			'require-yield': 'off',
			'no-shadow': 'off',
			'no-img-element': 'off',
			'react-in-jsx-scope': 'off',
			'exhaustive-deps': 'off',
			'effecttsgo/unstable-api-usage': 'off',
		},
		overrides: [
			{
				files: ['**/test/**', '**/test-backends/**', '**/*.test.ts'],
				rules: {
					'anti-slop-effect/no-manual-tagged-construction': 'off',
					'effecttsgo/node-builtin-import': 'off',
					'effecttsgo/run-effect-inside-effect': 'off',
					'effecttsgo/effect-succeed-with-void': 'off',
					'typescript/no-misused-spread': 'off',
				},
			},
			{
				files: ['packages/github/src/GitHubResources.ts'],
				rules: {
					'typescript/no-misused-spread': 'off',
				},
			},
			{
				files: ['packages/github/src/api/GitHubAppSigner.ts'],
				rules: {
					'automation/no-ambient-nondeterminism': 'off',
				},
			},
			{
				files: ['packages/delivery/src/Channels.ts'],
				rules: {
					'effecttsgo/any-unknown-in-error-context': 'off',
				},
			},
		],
	},
	fmt: {
		printWidth: 120,
		tabWidth: 4,
		useTabs: true,
		singleQuote: true,
		semi: false,
		sortImports: true,
		ignorePatterns: [
			'**/node_modules/**',
			'**/dist/**',
			'.agents/**',
			'.claude/**',
			'.humanlayer/**',
			'tools/oxlint/anti-slop/**',
			'tools/oxlint/automation/**',
			'tools/diff-check/**',
			'tools/typed/**',
		],
		sortPackageJson: true
	},
	run: {
		cache: true,
	},
})
